Traceback (most recent call last):
  File "c:\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "c:\anaconda3\lib\site-packages\nbclient\client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\anaconda3\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\anaconda3\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\anaconda3\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "c:\anaconda3\lib\site-packages\nbclient\client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "c:\anaconda3\lib\site-packages\nbclient\client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\anaconda3\lib\site-packages\nbclient\client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#4*x+3*y-4,2*x+2*y-2*z-0,5*x+3*y+z+2
eq1=input('enter an equation:')
eq2=input('enter an equation:')
eq3=input('enter an equation:')
from sympy.solvers import solve
from sympy import symbols
x,y,z=symbols('x,y,z')
ans=solve([eq1,eq2,eq3])
print('The solve to the question is:',ans)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mStdinNotImplementedError[0m                  Traceback (most recent call last)
[1;32m<ipython-input-3-dea8e18d9ab0>[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m [1;31m#4*x+3*y-4,2*x+2*y-2*z-0,5*x+3*y+z+2[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 2[1;33m [0meq1[0m[1;33m=[0m[0minput[0m[1;33m([0m[1;34m'enter an equation:'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      3[0m [0meq2[0m[1;33m=[0m[0minput[0m[1;33m([0m[1;34m'enter an equation:'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      4[0m [0meq3[0m[1;33m=[0m[0minput[0m[1;33m([0m[1;34m'enter an equation:'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      5[0m [1;32mfrom[0m [0msympy[0m[1;33m.[0m[0msolvers[0m [1;32mimport[0m [0msolve[0m[1;33m[0m[1;33m[0m[0m

[1;32mC:\Anaconda3\lib\site-packages\ipykernel\kernelbase.py[0m in [0;36mraw_input[1;34m(self, prompt)[0m
[0;32m    855[0m         """
[0;32m    856[0m         [1;32mif[0m [1;32mnot[0m [0mself[0m[1;33m.[0m[0m_allow_stdin[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 857[1;33m             raise StdinNotImplementedError(
[0m[0;32m    858[0m                 [1;34m"raw_input was called, but this frontend does not support input requests."[0m[1;33m[0m[1;33m[0m[0m
[0;32m    859[0m             )

[1;31mStdinNotImplementedError[0m: raw_input was called, but this frontend does not support input requests.
StdinNotImplementedError: raw_input was called, but this frontend does not support input requests.

